# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6dae692de04b6207ec05a3a4d3e0bea2b7e7aaae6eec25928ff0b99e8e05eb4bc420c8fbe0dc07298ed72b1683682f13497712bf02576439d02f9ca16aee81d

test:
  secret_key_base: ed0aca190a1fc66fbe76fa2f4d677fb978b0c07a17cbb429563b18574b191ddc9906ed10615c0989445ae39e7d82d80247036929b548a16f1535ca34c31ad6b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
